--- 
# roles/common-utils/tasks/fedora.yml
- name: Print pakages list
  debug:
    msg: "{{ list_utils }}"


#- name: Install epel-release
#  yum:
#    name: epel-release
#    state: present
#    update_cache: yes

- name: Install the list packages
  become: True
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    "{{ list_utils }}"